version: '3.8'

services:
  app:
    build: .
    ports:
      - "8020:8020"
    env_file:
      - .env
    volumes:
      - ./app:/app/app # Монтируем код приложения для разработки
    restart: unless-stopped
    networks:
      - postgre-network

networks:
  postgre-network:
    external: true